name: Build
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: muhdjau/altafashion:latest
      - 
        name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop project2
            docker rm project2
            docker rmi muhdjau/altafashion
            docker run --name project2 --link mysqlbe12 -d -p 8000:8000 -e DB_PORT=${{ secrets.DB_PORT }} -e DB_PWD=${{ secrets.DB_PWD }} -e DB_USER=${{ secrets.DB_USER }} -e DB_HOST=${{ secrets.DB_HOST }} -e DB_NAME=${{ secrets.DB_NAME }} -e JWT_SECRET=${{ secrets.JWT_SECRET }} -e AWS_KEY=${{ secrets.AWS_KEY }} -e AWS_USER=${{ secrets.AWS_USER }} -e AWS_REGION=${{ secrets.AWS_REGION }} muhdjau/altafashion
